/* Generated by src/tools/font_metrics.py from the Windows fonts (numbers only, no font data).
   asc/desc: GDI cell above/below the baseline in em (OS/2 usWinAscent/usWinDescent). digit: width of "0".
   fb: stand-in when the browser lacks the font (sel = Selawik, bsc = Barlow Semi Condensed). */
window.SP = window.SP || {};
SP.fontMetrics = {
  "Segoe UI": {"asc": 1.0791, "desc": 0.251, "cap": 0.7002, "digit": 0.5391, "space": 0.2739, "weight": 400, "fb": "sel"},
  "Segoe UI Light": {"asc": 1.0791, "desc": 0.251, "cap": 0.7002, "digit": 0.5151, "space": 0.2739, "weight": 300, "fb": "sel"},
  "Segoe UI Semilight": {"asc": 1.0791, "desc": 0.251, "cap": 0.7002, "digit": 0.5269, "space": 0.2739, "weight": 350, "fb": "sel"},
  "Segoe UI Semibold": {"asc": 1.0791, "desc": 0.251, "cap": 0.7002, "digit": 0.5552, "space": 0.2749, "weight": 600, "fb": "sel"},
  "Segoe UI Black": {"asc": 1.0791, "desc": 0.251, "cap": 0.7002, "digit": 0.5991, "space": 0.2778, "weight": 900, "fb": "sel"},
  "Bahnschrift": {"asc": 0.9941, "desc": 0.2061, "cap": 0.71, "digit": 0.5518, "space": 0.2686, "weight": 400, "fb": "bsc"},
  "Bahnschrift Light": {"asc": 0.9941, "desc": 0.2061, "cap": 0.71, "digit": 0.5518, "space": 0.2686, "weight": 300, "fb": "bsc"},
  "Bahnschrift SemiLight": {"asc": 0.9941, "desc": 0.2061, "cap": 0.71, "digit": 0.5518, "space": 0.2686, "weight": 350, "fb": "bsc"},
  "Bahnschrift SemiBold": {"asc": 0.9941, "desc": 0.2061, "cap": 0.71, "digit": 0.5518, "space": 0.2686, "weight": 600, "fb": "bsc"},
  "Consolas": {"asc": 0.9199, "desc": 0.251, "cap": 0.6382, "digit": 0.5498, "space": 0.5498, "weight": 400, "fb": "mono"},
  "Cascadia Mono": {"asc": 1.0869, "desc": 0.2344, "cap": 0.6934, "digit": 0.5859, "space": 0.5859, "weight": 400, "fb": "mono"},
  "Lucida Console": {"asc": 0.7891, "desc": 0.2109, "cap": 0.0, "digit": 0.6025, "space": 0.6025, "weight": 400, "fb": "mono"},
  "Courier New": {"asc": 0.8325, "desc": 0.3003, "cap": 0.5713, "digit": 0.6001, "space": 0.6001, "weight": 400, "fb": "mono"},
  "Arial": {"asc": 0.9053, "desc": 0.2119, "cap": 0.7163, "digit": 0.5562, "space": 0.2778, "weight": 400, "fb": "sans"},
  "Arial Narrow": {"asc": 0.9219, "desc": 0.2104, "cap": 0.0, "digit": 0.4561, "space": 0.228, "weight": 400, "fb": "sans"},
  "Calibri": {"asc": 0.9521, "desc": 0.2686, "cap": 0.6318, "digit": 0.5068, "space": 0.2261, "weight": 400, "fb": "sans"},
  "Calibri Light": {"asc": 0.9521, "desc": 0.2686, "cap": 0.6318, "digit": 0.5068, "space": 0.2261, "weight": 300, "fb": "sans"},
  "Tahoma": {"asc": 1.0005, "desc": 0.2065, "cap": 0.7271, "digit": 0.5459, "space": 0.3125, "weight": 400, "fb": "sans"},
  "Verdana": {"asc": 1.0054, "desc": 0.21, "cap": 0.7271, "digit": 0.6357, "space": 0.3516, "weight": 400, "fb": "sans"},
  "Trebuchet MS": {"asc": 0.939, "desc": 0.2222, "cap": 0.7153, "digit": 0.5244, "space": 0.3013, "weight": 400, "fb": "sans"},
  "Impact": {"asc": 1.0088, "desc": 0.2109, "cap": 0.7905, "digit": 0.5361, "space": 0.1763, "weight": 400, "fb": "sans"}
};
