"""Read the GDI line metrics of the Windows fonts the designer offers for live text and write
src/shared/fontmetrics.js. Only the numbers end up in the repository, never the fonts.

AIDA64 draws SIMPLE items and labels with GDI: ITMY is the top of the text cell, and the cell is
usWinAscent + usWinDescent (OS/2 table) tall. The preview needs those ratios per font.

Run:  uv run --with fonttools python src/tools/font_metrics.py
"""
import json
import os

from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, 'src', 'shared', 'fontmetrics.js')
FONTS = os.path.join(os.environ.get('WINDIR', r'C:\Windows'), 'Fonts')

# AIDA64 font name (GDI family) -> file, CSS weight, stand-in family when the browser lacks the font
FAMILIES = [
    ('Segoe UI', 'segoeui.ttf', 400, 'sel'),
    ('Segoe UI Light', 'segoeuil.ttf', 300, 'sel'),
    ('Segoe UI Semilight', 'segoeuisl.ttf', 350, 'sel'),
    ('Segoe UI Semibold', 'seguisb.ttf', 600, 'sel'),
    ('Segoe UI Black', 'seguibl.ttf', 900, 'sel'),
    ('Bahnschrift', 'bahnschrift.ttf', 400, 'bsc'),
    ('Bahnschrift Light', 'bahnschrift.ttf', 300, 'bsc'),
    ('Bahnschrift SemiLight', 'bahnschrift.ttf', 350, 'bsc'),
    ('Bahnschrift SemiBold', 'bahnschrift.ttf', 600, 'bsc'),
    ('Consolas', 'consola.ttf', 400, 'mono'),
    ('Cascadia Mono', 'CascadiaMono.ttf', 400, 'mono'),
    ('Lucida Console', 'lucon.ttf', 400, 'mono'),
    ('Courier New', 'cour.ttf', 400, 'mono'),
    ('Arial', 'arial.ttf', 400, 'sans'),
    ('Arial Narrow', 'ARIALN.TTF', 400, 'sans'),
    ('Calibri', 'calibri.ttf', 400, 'sans'),
    ('Calibri Light', 'calibril.ttf', 300, 'sans'),
    ('Tahoma', 'tahoma.ttf', 400, 'sans'),
    ('Verdana', 'verdana.ttf', 400, 'sans'),
    ('Trebuchet MS', 'trebuc.ttf', 400, 'sans'),
    ('Impact', 'impact.ttf', 400, 'sans'),
]


def metrics(path):
    f = TTFont(path, lazy=True)
    upem = f['head'].unitsPerEm
    os2 = f['OS/2']
    cmap = f.getBestCmap()
    hmtx = f['hmtx']
    digit = hmtx[cmap[ord('0')]][0] / upem
    space = hmtx[cmap[ord(' ')]][0] / upem
    r = lambda v: round(v, 4)
    return {'asc': r(os2.usWinAscent / upem), 'desc': r(os2.usWinDescent / upem),
            'cap': r(getattr(os2, 'sCapHeight', 0) / upem), 'digit': r(digit), 'space': r(space)}


def main():
    out = {}
    for name, file, weight, fallback in FAMILIES:
        path = os.path.join(FONTS, file)
        if not os.path.exists(path):
            print('missing', file)
            continue
        out[name] = {**metrics(path), 'weight': weight, 'fb': fallback}
    js = ('/* Generated by src/tools/font_metrics.py from the Windows fonts (numbers only, no font data).\n'
          '   asc/desc: GDI cell above/below the baseline in em (OS/2 usWinAscent/usWinDescent). digit: width of "0".\n'
          '   fb: stand-in when the browser lacks the font (sel = Selawik, bsc = Barlow Semi Condensed). */\n'
          'window.SP = window.SP || {};\n'
          'SP.fontMetrics = {\n' + ',\n'.join(f'  {json.dumps(k)}: {json.dumps(v)}' for k, v in out.items()) + '\n};\n')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(js)
    print(f'wrote {os.path.relpath(OUT, ROOT)} ({len(out)} fonts)')
    print('Segoe UI', out['Segoe UI'], 'expect asc 1.0791 desc 0.251')


if __name__ == '__main__':
    main()
